export interface ShelfItem {
  category_name: string;
  category_emoji: string;
  band: 'plenty' | 'low' | 'out';
  minutes_ago: number;
  confidence: number;
}

export interface Pantry {
  id: string;
  name: string;
  address: string;
  neighborhood: string;
  lat: number;
  lng: number;
  distance_miles: number;
  walk_minutes: number;
  hours_text: string;
  open_today: boolean;
  open_tonight: boolean;
  open_hours_display: string;
  requires_id: boolean;
  allows_walkins: boolean;
  languages: string[];
  notes: string;
  distribution_model: 'client_choice' | 'pre_packed' | 'list';
  shelf_items: ShelfItem[];
  phone: string;
}

export const BALTIMORE_PANTRIES: Pantry[] = [
  {
    id: 'a1000000-0000-0000-0000-000000000005',
    name: 'Northside Family Pantry',
    address: '1100 W 36th St, Baltimore, MD 21211',
    neighborhood: 'Hampden',
    lat: 39.3310,
    lng: -76.6362,
    distance_miles: 0.4,
    walk_minutes: 9,
    hours_text: 'Open tonight 5 to 8pm',
    open_today: true,
    open_tonight: true,
    open_hours_display: '5:00 PM – 8:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English', 'Spanish'],
    notes: 'Bring your own bags. Walk in, no appointment. You pick your own items, like a small store.',
    distribution_model: 'client_choice',
    phone: '(410) 555-0105',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 40, confidence: 0.95 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'low', minutes_ago: 40, confidence: 0.90 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'plenty', minutes_ago: 40, confidence: 0.95 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'plenty', minutes_ago: 40, confidence: 0.95 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'low', minutes_ago: 40, confidence: 0.85 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'out', minutes_ago: 40, confidence: 0.85 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 40, confidence: 0.92 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 40, confidence: 0.95 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000006',
    name: 'Riverside Community Table',
    address: '1234 E Fort Ave, Baltimore, MD 21230',
    neighborhood: 'Riverside',
    lat: 39.2720,
    lng: -76.5960,
    distance_miles: 0.7,
    walk_minutes: 15,
    hours_text: 'Open tonight 4 to 7pm',
    open_today: true,
    open_tonight: true,
    open_hours_display: '4:00 PM – 7:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English', 'Spanish'],
    notes: 'Pre-packed bags. Drive-through or walk-in available.',
    distribution_model: 'pre_packed',
    phone: '(410) 555-0106',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 110, confidence: 0.85 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'low', minutes_ago: 110, confidence: 0.80 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'plenty', minutes_ago: 110, confidence: 0.85 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'low', minutes_ago: 110, confidence: 0.75 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'out', minutes_ago: 110, confidence: 0.70 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'low', minutes_ago: 110, confidence: 0.75 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 110, confidence: 0.85 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 110, confidence: 0.90 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000008',
    name: 'Waverly Community Pantry',
    address: '3100 Greenmount Ave, Baltimore, MD 21218',
    neighborhood: 'Waverly',
    lat: 39.3270,
    lng: -76.6095,
    distance_miles: 1.2,
    walk_minutes: 24,
    hours_text: 'Open today 2 to 6pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '2:00 PM – 6:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English'],
    notes: 'Walk in, no appointment. Bring your own bags.',
    distribution_model: 'client_choice',
    phone: '(410) 555-0108',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'low', minutes_ago: 25, confidence: 0.85 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'low', minutes_ago: 25, confidence: 0.80 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'plenty', minutes_ago: 25, confidence: 0.90 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'plenty', minutes_ago: 25, confidence: 0.90 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'low', minutes_ago: 25, confidence: 0.75 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'low', minutes_ago: 25, confidence: 0.80 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 25, confidence: 0.88 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 25, confidence: 0.90 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000001',
    name: 'Beans and Bread',
    address: '402 S Bond St, Baltimore, MD 21231',
    neighborhood: 'Fells Point',
    lat: 39.2830,
    lng: -76.5925,
    distance_miles: 2.1,
    walk_minutes: 42,
    hours_text: 'Open Mon-Fri 10am to 2pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '10:00 AM – 2:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English', 'Spanish'],
    notes: 'Bring two or three sturdy bags. Fresh grocery pantry and warm meals.',
    distribution_model: 'client_choice',
    phone: '(410) 732-6834',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 35, confidence: 0.95 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'low', minutes_ago: 35, confidence: 0.90 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'plenty', minutes_ago: 35, confidence: 0.95 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'low', minutes_ago: 35, confidence: 0.85 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'low', minutes_ago: 35, confidence: 0.80 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'out', minutes_ago: 35, confidence: 0.85 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 35, confidence: 0.95 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 35, confidence: 0.95 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000002',
    name: 'GEDCO CARES Pantry',
    address: '5765 N Charles St, Baltimore, MD 21210',
    neighborhood: 'Charles Village',
    lat: 39.3490,
    lng: -76.6131,
    distance_miles: 1.8,
    walk_minutes: 36,
    hours_text: 'Open Tue & Thu 9am to 12pm',
    open_today: false,
    open_tonight: false,
    open_hours_display: '9:00 AM – 12:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English'],
    notes: 'Pick from our list and volunteers pack it for you.',
    distribution_model: 'list',
    phone: '(410) 243-0855',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'low', minutes_ago: 95, confidence: 0.80 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'plenty', minutes_ago: 95, confidence: 0.85 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'low', minutes_ago: 95, confidence: 0.80 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'out', minutes_ago: 95, confidence: 0.80 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'out', minutes_ago: 95, confidence: 0.75 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'low', minutes_ago: 95, confidence: 0.80 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 95, confidence: 0.85 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 95, confidence: 0.85 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000003',
    name: 'St. Vincent de Paul Food Pantry',
    address: '120 N Front St, Baltimore, MD 21202',
    neighborhood: 'Jonestown',
    lat: 39.2920,
    lng: -76.6050,
    distance_miles: 2.5,
    walk_minutes: 50,
    hours_text: 'Open Wed 10am-1pm, Sat 9am-12pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '10:00 AM – 1:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English', 'Spanish'],
    notes: 'Pre-packed emergency pantry bags ready to go. No appointment required.',
    distribution_model: 'pre_packed',
    phone: '(410) 962-5078',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'plenty', minutes_ago: 15, confidence: 0.95 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 15, confidence: 0.98 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000004',
    name: 'Bea Gaddy Family Centers',
    address: '413 E Federal St, Baltimore, MD 21202',
    neighborhood: 'Patterson Park',
    lat: 39.2960,
    lng: -76.5960,
    distance_miles: 2.8,
    walk_minutes: 55,
    hours_text: 'Open Mon, Wed, Fri 9am to 3pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '9:00 AM – 3:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English'],
    notes: 'You pick your own items, like a small grocery store.',
    distribution_model: 'client_choice',
    phone: '(410) 563-2749',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'low', minutes_ago: 60, confidence: 0.70 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'out', minutes_ago: 60, confidence: 0.65 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'low', minutes_ago: 60, confidence: 0.70 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'low', minutes_ago: 60, confidence: 0.65 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'out', minutes_ago: 60, confidence: 0.55 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'out', minutes_ago: 60, confidence: 0.60 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 60, confidence: 0.75 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'low', minutes_ago: 60, confidence: 0.70 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000007',
    name: 'Paul\'s Place',
    address: '1118 Ward St, Baltimore, MD 21230',
    neighborhood: 'Pigtown',
    lat: 39.2790,
    lng: -76.6350,
    distance_miles: 3.1,
    walk_minutes: 62,
    hours_text: 'Open Mon-Fri 8:30am to 12:30pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '8:30 AM – 12:30 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English'],
    notes: 'Hot breakfast, clothing boutique, and marketplace pantry.',
    distribution_model: 'client_choice',
    phone: '(410) 625-0775',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 20, confidence: 0.95 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'plenty', minutes_ago: 20, confidence: 0.95 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'low', minutes_ago: 20, confidence: 0.90 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'out', minutes_ago: 20, confidence: 0.95 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'plenty', minutes_ago: 20, confidence: 0.90 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'plenty', minutes_ago: 20, confidence: 0.95 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 20, confidence: 0.95 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 20, confidence: 0.95 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000009',
    name: 'Cherry Hill Community Pantry',
    address: '601 Cherry Hill Rd, Baltimore, MD 21225',
    neighborhood: 'Cherry Hill',
    lat: 39.2460,
    lng: -76.6230,
    distance_miles: 4.2,
    walk_minutes: 84,
    hours_text: 'Open Fri & Sat 10am to 2pm',
    open_today: false,
    open_tonight: false,
    open_hours_display: '10:00 AM – 2:00 PM',
    requires_id: true,
    allows_walkins: true,
    languages: ['English'],
    notes: 'ID required for first visit. Pre-packed family boxes.',
    distribution_model: 'pre_packed',
    phone: '(410) 555-0109',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'low', minutes_ago: 180, confidence: 0.60 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'low', minutes_ago: 180, confidence: 0.60 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'out', minutes_ago: 180, confidence: 0.50 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'out', minutes_ago: 180, confidence: 0.50 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'out', minutes_ago: 180, confidence: 0.40 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'out', minutes_ago: 180, confidence: 0.45 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'low', minutes_ago: 180, confidence: 0.60 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'low', minutes_ago: 180, confidence: 0.60 },
    ]
  },
  {
    id: 'a1000000-0000-0000-0000-000000000010',
    name: 'Sandtown Community Pantry',
    address: '1400 N Mount St, Baltimore, MD 21217',
    neighborhood: 'Sandtown-Winchester',
    lat: 39.3060,
    lng: -76.6420,
    distance_miles: 1.9,
    walk_minutes: 38,
    hours_text: 'Open Mon & Thu 11am to 3pm',
    open_today: true,
    open_tonight: false,
    open_hours_display: '11:00 AM – 3:00 PM',
    requires_id: false,
    allows_walkins: true,
    languages: ['English'],
    notes: 'You pick your own items. No ID needed.',
    distribution_model: 'client_choice',
    phone: '(410) 555-0110',
    shelf_items: [
      { category_name: 'Produce', category_emoji: '🥕', band: 'plenty', minutes_ago: 45, confidence: 0.85 },
      { category_name: 'Protein', category_emoji: '🥩', band: 'plenty', minutes_ago: 45, confidence: 0.85 },
      { category_name: 'Dairy', category_emoji: '🥛', band: 'low', minutes_ago: 45, confidence: 0.80 },
      { category_name: 'Diapers', category_emoji: '🧒', band: 'low', minutes_ago: 45, confidence: 0.75 },
      { category_name: 'Halal items', category_emoji: '🌙', band: 'low', minutes_ago: 45, confidence: 0.75 },
      { category_name: 'Hygiene', category_emoji: '🧴', band: 'out', minutes_ago: 45, confidence: 0.70 },
      { category_name: 'Grains', category_emoji: '🍞', band: 'plenty', minutes_ago: 45, confidence: 0.85 },
      { category_name: 'Canned Goods', category_emoji: '🥫', band: 'plenty', minutes_ago: 45, confidence: 0.85 },
    ]
  }
];
